export const MESSAGE = {
    GLOBAL: {
        NOT_FOUND: "Data tidak ditemukan.",
        INTERNAL_SERVER_ERROR: "Terjadi kesalahan pada server.",
        UNAUTHORIZED: "Anda belum masuk.",
        BAD_REQUEST: "Data tidak valid.",
        FORBIDDEN: "Anda tidak memiliki izin untuk melakukan aksi ini.",
        NOT_IMPLEMENTED: "Fitur ini belum diimplementasikan.",
        TRY_AGAIN_BUTTON: "Coba lagi.",
    },
    AUTH: {
        SIGN_IN_OK: "Anda berhasil masuk.",
        SIGN_IN_INCORRECT: "Email atau password salah.",
        SIGN_IN_NOT_VERIFIED: "Email belum terverifikasi.",
        SIGN_IN_NOT_ACTIVE: "Akun tidak aktif, hubungi admin.",
        SIGN_UP_OK: "Anda berhasil mendaftar, cek email untuk verifikasi.",
        SIGN_UP_ALREADY_EXISTS: "Email sudah terdaftar.",
        SIGN_OUT_OK: "Anda berhasil keluar.",
        EMAIL_NOT_FOUND: "Email tidak terdaftar.",
        FORGOT_OK: "Permintaan lupa password berhasil.",
        EMAIL_VERIFICATION_OK: "Permintaan verifikasi email berhasil.",
        EMAIL_VERIFICATION_ALREADY_USED: "Verifikasi email sudah digunakan.",
        EMAIL_VERIFICATION_EXPIRED: "Verifikasi email sudah expired.",
        EMAIL_VERIFICATION_NOT_FOUND: "Verifikasi email tidak ditemukan.",
        RESET_PASSWORD_OK: "Berhasil mereset password.",
        RESET_PASSWORD_FAIL: "Gagal mereset password.",
        UNAUTHORIZED: "Anda belum masuk.",
    },
    USER: {
        CREATE_OK: "Berhasil membuat data user.",
        CREATE_FAIL: "Gagal membuat data user.",
        CREATE_FAIL_UNIQUE: "Gagal membuat data user karena email sudah terdaftar.",
        UPDATE_OK: "Berhasil mengupdate data user.",
        UPDATE_FAIL: "Gagal mengupdate data user.",
        DELETE_OK: "Berhasil menghapus data user.",
        DELETE_FAIL: "Gagal menghapus data user.",
        APPROVE_OK: "Berhasil mengapprove data user.",
        APPROVE_FAIL: "Gagal mengapprove data user.",
        REJECT_OK: "Berhasil menolak data user.",
        REJECT_FAIL: "Gagal menolak data user.",
        RESET_PASSWORD_OK: "Berhasil mereset password.",
        RESET_PASSWORD_FAIL: "Gagal mereset password.",
        CHANGE_STATUS_OK: "Berhasil mengubah status user.",
        CHANGE_STATUS_FAIL: "Gagal mengubah status user.",
        CHANGE_ROLE_OK: "Berhasil mengubah role user.",
        CHANGE_ROLE_FAIL: "Gagal mengubah role user.",
        FIND_MANY_ERROR_HEADER: "Gagal mendapatkan data user.",
        FIND_MANY_ERROR_DESCRIPTION: "Terjadi kesalahan pada server.",
    },
    KTP_REQUEST: {
        CREATE_OK: "Berhasil membuat data permohonan KTP.",
        CREATE_FAIL: "Gagal membuat data permohonan KTP.",
        UPDATE_OK: "Berhasil mengupdate data permohonan KTP.",
        UPDATE_FAIL: "Gagal mengupdate data permohonan KTP.",
        DELETE_OK: "Berhasil menghapus data permohonan KTP.",
        DELETE_FAIL: "Gagal menghapus data permohonan KTP.",
        APPROVE_OK: "Berhasil mengapprove data permohonan KTP.",
        APPROVE_FAIL: "Gagal mengapprove data permohonan KTP.",
        REJECT_OK: "Berhasil menolak data permohonan KTP.",
        REJECT_FAIL: "Gagal menolak data permohonan KTP.",
        CHANGE_STATUS_OK: "Berhasil mengubah status permohonan KTP.",
        CHANGE_STATUS_FAIL: "Gagal mengubah status permohonan KTP.",
        FOLLOW_UP_OK: "Berhasil tindak lanjut data permohonan KTP.",
        FOLLOW_UP_FAIL: "Gagal tindak lanjut data permohonan KTP.",
    },
    SKL_REQUEST: {
        CREATE_OK: "Berhasil membuat data permohonan SKL.",
        CREATE_FAIL: "Gagal membuat data permohonan SKL.",
        UPDATE_OK: "Berhasil mengupdate data permohonan SKL.",
        UPDATE_FAIL: "Gagal mengupdate data permohonan SKL.",
        DELETE_OK: "Berhasil menghapus data permohonan SKL.",
        DELETE_FAIL: "Gagal menghapus data permohonan SKL.",
        APPROVE_OK: "Berhasil mengapprove data permohonan SKL.",
        APPROVE_FAIL: "Gagal mengapprove data permohonan SKL.",
        REJECT_OK: "Berhasil menolak data permohonan SKL.",
        REJECT_FAIL: "Gagal menolak data permohonan SKL.",
        UPDATE_STATUS_OK: "Berhasil mengubah status permohonan SKL.",
        UPDATE_STATUS_FAIL: "Gagal mengubah status permohonan SKL.",
    },
    SKTM_REQUEST: {
        CREATE_OK: "Berhasil membuat data permohonan SKTM.",
        CREATE_FAIL: "Gagal membuat data permohonan SKTM.",
        UPDATE_OK: "Berhasil mengupdate data permohonan SKTM.",
        UPDATE_FAIL: "Gagal mengupdate data permohonan SKTM.",
        DELETE_OK: "Berhasil menghapus data permohonan SKTM.",
        DELETE_FAIL: "Gagal menghapus data permohonan SKTM.",
        UPDATE_STATUS_OK: "Berhasil mengubah status permohonan SKTM.",
        UPDATE_STATUS_FAIL: "Gagal mengubah status permohonan SKTM.",
    },
    SKK_REQUEST: {
        CREATE_OK: "Berhasil membuat data permohonan SKK.",
        CREATE_FAIL: "Gagal membuat data permohonan SKK.",
        UPDATE_OK: "Berhasil mengupdate data permohonan SKK.",
        UPDATE_FAIL: "Gagal mengupdate data permohonan SKK.",
        DELETE_OK: "Berhasil menghapus data permohonan SKK.",
        DELETE_FAIL: "Gagal menghapus data permohonan SKK.",
        UPDATE_STATUS_OK: "Berhasil mengubah status permohonan SKK.",
        UPDATE_STATUS_FAIL: "Gagal mengubah status permohonan SKK.",
    },
    PERMOHONAN_SKU: {
        CREATE_OK: "Berhasil membuat data permohonan SKU.",
        CREATE_FAIL: "Gagal membuat data permohonan SKU.",
        UPDATE_OK: "Berhasil mengupdate data permohonan SKU.",
        UPDATE_FAIL: "Gagal mengupdate data permohonan SKU.",
        DELETE_OK: "Berhasil menghapus data permohonan SKU.",
        DELETE_FAIL: "Gagal menghapus data permohonan SKU.",
        UPDATE_STATUS_OK: "Berhasil mengubah status permohonan SKU.",
        UPDATE_STATUS_FAIL: "Gagal mengubah status permohonan SKU.",
        NOT_FOUND: "Data permohonan SKU tidak ditemukan.",
    },
    PERMOHONAN_SKD: {
        CREATE_OK: "Berhasil membuat data permohonan SKD.",
        CREATE_FAIL: "Gagal membuat data permohonan SKD.",
        UPDATE_OK: "Berhasil mengupdate data permohonan SKD.",
        UPDATE_FAIL: "Gagal mengupdate data permohonan SKD.",
        DELETE_OK: "Berhasil menghapus data permohonan SKD.",
        DELETE_FAIL: "Gagal menghapus data permohonan SKD.",
        UPDATE_STATUS_OK: "Berhasil mengubah status permohonan SKD.",
        UPDATE_STATUS_FAIL: "Gagal mengubah status permohonan SKD.",
        NOT_FOUND: "Data permohonan SKD tidak ditemukan.",
    },
    PERMOHONAN_PINDAH: {
        CREATE_OK: "Berhasil membuat data permohonan pindah.",
        CREATE_FAIL: "Gagal membuat data permohonan pindah.",
        UPDATE_OK: "Berhasil mengupdate data permohonan pindah.",
        UPDATE_FAIL: "Gagal mengupdate data permohonan pindah.",
        DELETE_OK: "Berhasil menghapus data permohonan pindah.",
        DELETE_FAIL: "Gagal menghapus data permohonan pindah.",
        UPDATE_STATUS_OK: "Berhasil mengubah status permohonan pindah.",
        UPDATE_STATUS_FAIL: "Gagal mengubah status permohonan pindah.",
        NOT_FOUND: "Data permohonan pindah tidak ditemukan.",
    },
}