export const VALIDATION_MESSAGE = {
 INVALID_EMAIL: "Email tidak valid",
 INVALID_PASSWORD: "Kata sandi harus terdiri dari minimal 8 karakter",
 INVALID_NIK: "NIK harus terdiri dari minimal 16 karakter",
 INVALID_NAME: "Nama harus terdiri dari minimal 3 karakter",
 INVALID_ADDRESS: "Alamat harus terdiri dari minimal 3 karakter",
 INVALID_PHONE: "Nomor telepon harus terdiri dari minimal 10 karakter",
 INVALID_PROVINCE: "Provinsi harus terdiri dari minimal 1 karakter",
 INVALID_REGENCY: "Kabupaten harus terdiri dari minimal 1 karakter",
 INVALID_DISTRICT: "Kecamatan harus terdiri dari minimal 1 karakter",
 INVALID_VILLAGE: "Desa harus terdiri dari minimal 1 karakter",
 INVALID_PROVINCE_CODE: "Kode provinsi harus terdiri dari minimal 2 karakter",
 INVALID_REGENCY_CODE: "Kode kabupaten harus terdiri dari minimal 2 karakter",
 INVALID_DISTRICT_CODE: "Kode kecamatan harus terdiri dari minimal 2 karakter",
 INVALID_VILLAGE_CODE: "Kode desa harus terdiri dari minimal 4 karakter",
 INVALID_ZIP_CODE: "Kode pos harus terdiri dari minimal 5 karakter",
 INVALID_RT: "RT harus terdiri dari minimal 3 karakter",
 INVALID_RW: "RW harus terdiri dari minimal 3 karakter",
 INVALID_KK_DOCUMENT: "Format URL tidak valid",
 INVALID_KTP_DOCUMENT: "Format URL tidak valid",
 INVALID_PENGANTAR_DOCUMENT: "Format URL tidak valid",
 INVALID_BIRTH_PLACE: "Tempat lahir harus terdiri dari minimal 1 karakter",
 INVALID_NOTE: "Catatan harus terdiri dari minimal 1 karakter",
}
